// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using webgiris2.repositories;

#nullable disable

namespace webgiris2.Migrations
{
    [DbContext(typeof(RepositoriyContext))]
    [Migration("20250312113648_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("webgiris2.Models.dene", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("age")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Denes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "kemal",
                            age = 10
                        },
                        new
                        {
                            Id = 2,
                            Name = "osman",
                            age = 80
                        },
                        new
                        {
                            Id = 3,
                            Name = "Ali",
                            age = 50
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
